# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 16:42
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=15)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('orden', models.CharField(blank=True, max_length=10)),
                ('edicion', models.IntegerField(blank=True, null=True)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField(default=datetime.datetime.today)),
                ('fechaFin', models.DateField(default=datetime.datetime(2016, 8, 13, 16, 42, 44, 227629))),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Libros')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellidos', models.CharField(max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('direccion', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='prestamo',
            name='usuarioPrestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Usuario'),
        ),
    ]
