# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 19:56
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField(default=datetime.datetime.today)),
                ('fechaFin', models.DateField(default=datetime.datetime(2016, 8, 18, 19, 56, 32, 303411))),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('codigo', models.CharField(blank=True, max_length=100)),
                ('estanteria', models.CharField(blank=True, max_length=100)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('editorial', models.CharField(blank=True, max_length=250)),
                ('dvd', models.BooleanField(default=False)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellidos', models.CharField(max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Telefono debe ser: 123456789.', regex='^\\d{9,15}$')])),
                ('direccion', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='prestamo',
            name='Recurso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Recurso'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='usuarioPrestamo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Usuario'),
        ),
    ]
