# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 17:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20160806_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Recurso',
            name='autor',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2016, 8, 13, 17, 7, 27, 853185)),
        ),
    ]
