# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 23:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20160811_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2016, 8, 18, 23, 22, 30, 845714)),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='titulo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
