# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 23:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20160811_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2016, 8, 18, 23, 31, 31, 583919)),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
