# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 17:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20160806_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2016, 8, 13, 17, 10, 38, 486145)),
        ),
    ]
