# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 19:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20160811_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2016, 8, 24, 19, 16, 34, 751053)),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
