# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 19:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_auto_20160817_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2016, 8, 24, 19, 40, 50, 906124)),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
