# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 14:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_auto_20160927_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2016, 10, 4, 14, 55, 50, 669012)),
        ),
    ]
