# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 16:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_auto_20160927_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2016, 10, 4, 16, 25, 54, 745059)),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='autor',
            field=models.CharField(max_length=300),
        ),
    ]
