# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 16:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_auto_20160927_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2016, 10, 4, 16, 30, 1, 824032)),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='codigo',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
