# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 19:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_auto_20160806_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2016, 8, 13, 19, 24, 41, 430917)),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='Recurso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Recurso'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='usuarioPrestamo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Usuario'),
        ),
    ]
