# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 17:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0012_auto_20160927_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2016, 10, 4, 17, 43, 22, 137255)),
        ),
    ]
