# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 18:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0017_auto_20160807_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='dvd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2016, 8, 14, 18, 36, 3, 907433)),
        ),
    ]
