# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 19:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0018_auto_20160807_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2016, 8, 14, 19, 13, 4, 663804)),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='autor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
