# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 19:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0022_auto_20160807_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genero',
            name='id',
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2016, 8, 14, 19, 35, 11, 525043)),
        ),
    ]
