# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 14:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0024_auto_20160807_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2016, 8, 15, 14, 5, 55, 701249)),
        ),
    ]
