# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 16:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0025_auto_20160808_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='editorial',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='recurso',
            name='estanteria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recurso',
            name='fecha',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2016, 8, 15, 16, 26, 19, 256076)),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='orden',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
