# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 16:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0026_auto_20160808_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2016, 8, 15, 16, 27, 59, 105831)),
        ),
    ]
