# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 19:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0027_auto_20160808_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2016, 8, 15, 19, 51, 4, 268843)),
        ),
    ]
