# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 20:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0028_auto_20160808_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2016, 8, 15, 20, 16, 1, 971673)),
        ),
    ]
